language: python

python:
    - "3.5"

global:
    secure: AtQt44k4iw03KZXCgAIU6UXZ9Tp7ereM7TRA+D0wTMqAdieGkz1GSt4Ecz3V+qCCk2LY1ZsP3wGgaOkrqePxGospkKluGPEya+5kr+OcJ1PbwBJY/dV3CC0MdfdUqkwHMaBhX4ZBkL0HbKKTjsAmRYb0QrLU2ln5l2GJVRVkElWp+DRSfhkC0Mjl5w9heqkNZisFuksJ9pMN2bYGGPMFN6ImrxEQSfUIhTOmiAuzsjFIMYoJk0virQRLlFDOUEkGzQPARtCRPMheTaNRmYj2wgfYA0NxVhrk4RY522dd5fVgiW6D9RnsaURAKaVr/mBTTfFHWrfKuBK5p4+Rjt4160n5vtDH087F8OiDETri994QgIy0OvL/kqknAWoOvksQuNtV2ra4TTM0KDjXNIswgRCG1lzLvfn7Z9chmS3/ySfO6xdEwtXm/bOYINrZXOux7wKbkyHJc50iW4xcvILlCqJUNSlwZdHPDUWqECQq6hMWpZPL8XWxwsjGjU3ttispw2vw5mSzFiie89kqZgfMbAauI5ybw5GoT4DKJU5D295IhErn0JWomxS0dZZx8RuyiqffWuIu0H5gj56o6K7u+KkFCISIhbn0PKIih77XUbIZrRD0wdl0zBa8Lj2M75GjuHa/CnVBRgCptYnGrEfWmy8OD8/hKyN1hgKFfH32Qwc=

matrix:
  include:
    - services:
      - docker

      sudo: required

      cache:
        - directories:
          - node_modules
          - course_discovery/static/bower_components

      before_install:
          - make travis_up

      install:
        - docker exec -t discovery bash -c 'apt update && apt install -y xvfb firefox gettext wget'
        - docker exec -t discovery bash -c 'sed -i "s/course_discovery.settings.devstack/course_discovery.settings.test/" /edx/app/discovery/discovery_env'
        - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && make requirements'

      script:
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && make docs'
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && make validate_translations'
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && make clean_static'
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && make static'
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && make quality'
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && xvfb-run make test'

      after_success:
          - pip install -U codecov
          - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/ && coverage xml'
          - codecov

    - script:
        - python .travis/check_master_build.py --commit $TRAVIS_COMMIT --github_status_token $GITHUB_STATUS_TOKEN --travis_api_token $TRAVIS_API_TOKEN
