# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0078_merge_20180209_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bulk_sku',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
